version: '2'
services:
    smevents-app:
        image: smevents
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smevents-mysql:3306/smevents?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smevents-mysql:
        extends:
            file: mysql.yml
            service: smevents-mysql
